hosman/urls.py
from django.contrib import admin
from django.urls import path, include
from editorial.admin import editorial
from hosman_web.admin import hcare


urlpatterns = [
    path('admin/', include('editorial.urls')),
    path('', include('hosman_web.urls')),
    path('su/', hcare.urls),
    path('site/', include('editorial.man_urls'))
]

hosman_web/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from .views import *
from .views_profile import *
from .views_accounts import *
from .views_ajax import *
from .search import SearchView
from .admin import hcare

app_name = 'hosman_web'
urlpatterns = [
        path('su/', hcare.urls),
        #path('emergency/', EmergencyView.as_view(), name='emergency'),
        path('thanks/', ThankYouView),
        path('media/', GContentView.as_view()),
        #####################################################################################################################
        # ajax views
        #####################################################################################################################
        #path('emergency/', EmergencyView.as_view(), name='emergency'),
        path('get/search/', SearchView.as_view(), name='get-search'),
        #####################################################################################################################
        # ajax views
        #####################################################################################################################
        #path('emergency/', EmergencyView.as_view(), name='emergency'),
        path('ajax/validate_username/', validate_username, name='validate-username'),
        path('ajax/query_search/', query_search, name='query-search'),
        #####################################################################################################################
        # accounts views
        #####################################################################################################################
        #path('emergency/', EmergencyView.as_view(), name='emergency'),
        path('accounts/profile/<slug:slug>/', UserProfileView.as_view(), name='user-profile'),
        path('accounts/profile/', get_profile_view, name="get-profile"),
        path('accounts/signup/', UserCreationView.as_view(), name='sign-up'),
        path('accounts/profile/setup_wiz/update_info/', UpdateProfileView.as_view(), name='update-profile-info'),
        path('accounts/profile/setup_wiz/update_info/profile_picture/', ProfilePictureView.as_view(), name='add-profile-picture'),
        path('accounts/', include('django.contrib.auth.urls')),
        path('accounts/login/', CLoginView.as_view(), name='login'), # accounts/login/ [name='login']
        path('accounts/logout/', CLogoutView.as_view(), name='logout'), # accounts/logout/ [name='logout']
        #includes the following path
        # accounts/password_change/ [name='password_change']
        # accounts/password_change/done/ [name='password_change_done']
        # accounts/password_reset/ [name='password_reset']
        # accounts/password_reset/done/ [name='password_reset_done']
        # accounts/reset/<uidb64>/<token>/ [name='password_reset_confirm']
        # accounts/reset/done/ [name='password_reset_complete']
        path('', IndexView.as_view(), name='index'),
        path('home/', HomeView.as_view(), name='home'),
]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

editorial/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from .storage import fs
from hosman_web.models import Patient, Address
from domains.models import Domain

# Create your models here.

class SearchString(models.Model):
    string = models.CharField(max_length=500)
    doctor = models.BooleanField(default=False)
    schedule = models.BooleanField(default=False)
    facility = models.BooleanField(default=False)
    q_count = models.IntegerField(default=-1)
    def save(self, *args, **kwargs):
        self.q_count += 1
        super(SearchString, self).save(*args, **kwargs)

class BinTray(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    bin_text = models.CharField(max_length=100)
    bin_detail = models.CharField(max_length=500, null=True, blank=True)
    bin_item = models.CharField(max_length=500)

class ScheduleRequest(models.Model):
    schedule = models.ForeignKey('Schedule', on_delete=models.CASCADE)
    made_by = models.ForeignKey(Patient, on_delete=models.SET_NULL, null=True, blank=True)
    class CreateUpdate(models.TextChoices):
        CREATE = 'C', _('Create')
        UPDATE = 'U', _("Update")
        RETAINED = "R", ("Retained")
    request = models.CharField(max_length=1, choices=CreateUpdate.choices, default=CreateUpdate.CREATE)
    approve = models.BooleanField(default=False)
    ref_id = models.IntegerField(null=True, blank=True)
    def __str__(self):
        return self.schedule.__str__()

class MembershipRequest(models.Model):
    class Membership(models.TextChoices):
        SITEMANAGER = "SM", _('Site Manager')
        SITEEMPLOYEE = "SE", _('General Employee')
        DOCTOR = "DR", _('Doctor')
        NURSE = "NS", _('Nurse')
    request_for = models.CharField(max_length=2, choices=Membership.choices, default=Membership.DOCTOR)
    doctor = models.OneToOneField("Doctor", on_delete=models.SET_NULL, null=True, blank=True)
    nurse = models.OneToOneField("Nurse", on_delete=models.SET_NULL, null=True, blank=True)
    employee = models.OneToOneField("Employee", on_delete=models.SET_NULL, null=True, blank=True)
    site_manager = models.OneToOneField("SiteManager", on_delete=models.SET_NULL, null=True, blank=True)
    def __str__(self):
        if self.doctor is not None:
            username = self.doctor.patient.user.username
            r_for = "Doctor"
        elif self.nurse is not None:
            username = self.nurse.patient.user.username
            r_for = "Nurse"
        elif self.employee is not None:
            username = self.employee.patient.user.username
            r_for = "Site Employee"
        elif self.site_manager is not None:
            username = self.site_manager.patient.user.username
            r_for = "Site Manager"
        else:
            return "Something really went wrong!"
        return "Membership Request for " + r_for + " from " + username

class SiteManager(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    class Designation(models.TextChoices):
        SITEADMIN = "SA", _("Site Administrator")
        SITEMANAGER = "SM", _("Site Manager")
        SITETECHIE = "ST", _("Site Techie")
    designation = models.CharField(max_length=2, choices=Designation.choices, default=Designation.SITEADMIN)
    site = models.ForeignKey('Center', on_delete=models.SET_NULL, null=True, blank=True)
    def __str__(self):
        return self.patient.user.__str__()

class Hospital(models.Model):
    name = models.CharField(max_length=300)
    identifier = models.CharField(max_length=128, unique=True)
    domain = models.ForeignKey(Domain, on_delete=models.CASCADE)
    def __str__(self):
        return self.name
    
class Department(models.Model):
    class DepartmentChoices(models.TextChoices):
        VISIT = "Visiting Center"
        WARD = "Ward Center"
        EMERGENGY = "Emergergy Center"
        SURGERY = "Surgical Center"
        DIAGNOSTIC = "Diagnostic Center"
        DEFAULT = "default"
    name = models.CharField(max_length=20, choices=DepartmentChoices.choices)
    def __str__(self):
        return self.name

class Branch(models.Model):
    name = models.CharField(max_length=80, unique=True)
    address = models.ForeignKey(Address, on_delete=models.SET_NULL, null=True, blank=True)
    phone = models.CharField(
        max_length=20,
        null=True,
        blank=True
        )
    email = models.EmailField(
        max_length=250,
        null=True,
        blank=True
        )
    hospital = models.ForeignKey(
        Hospital,
        on_delete=models.CASCADE
        )
    def __str__(self):
        return self.hospital.name + '; ' + self.address.__str__()

class Center(models.Model):
    building_name = models.CharField(max_length=180, null=True, blank=True)
    site_manager = models.ForeignKey('SiteManager', on_delete=models.SET_NULL, null=True, blank=True,)
    branch = models.ForeignKey(Branch, on_delete=models.CASCADE)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    description = models.CharField(max_length=400, null=True, blank=True, editable=False)
    def __str__(self):
        return self.description
    def save(self, *args, **kwargs):
        self.description = self.branch.hospital.name+' ('+self.department.name+'); '+ self.branch.address.__str__()
        super(Center, self).save(*args, **kwargs)

class Doctor(models.Model):
    patient = models.OneToOneField(Patient, on_delete=models.CASCADE)
    assigned_to = models.ForeignKey('Center', on_delete=models.SET_NULL, null=True, blank=True)
    specializations = models.ManyToManyField('Specialization')
    def __str__(self):
        return self.patient.__str__()

class Nurse(models.Model):
    patient = models.OneToOneField(Patient, on_delete=models.CASCADE)
    assigned_to = models.ForeignKey('Center', on_delete=models.SET_NULL, null=True, blank=True)
    def __str__(self):
        return self.patient.__str__()

class Employee(models.Model):
    patient = models.OneToOneField(Patient, on_delete=models.CASCADE)
    class EDesignation(models.TextChoices):
        OTHER = 'OR', _('Other')
        MANAGER = 'MR', _('Manager')
        RECEPTIONIST = 'RT', _('Receptionist')
    designation = models.CharField(max_length=2, choices=EDesignation.choices, default=EDesignation.OTHER)
    assigned_to = models.ForeignKey(Center, on_delete=models.SET_NULL, null=True, blank=True)
    def __str__(self):
        return self.patient.__str__()

class Specialization(models.Model):
    category = models.CharField(max_length=30)
    name = models.CharField(max_length=30)
    class SpecClass(models.IntegerChoices):
        DOCTOR = 1
        NURSE = 0
    class_doctor = models.IntegerField(choices=SpecClass.choices, default=SpecClass.DOCTOR)
    def __str__(self):
        return self.name

class HistoricalRecord(models.Model):
    date = models.DateField()
    receipt_no = models.CharField(max_length=50, null=True, blank=True)
    class TypeTest(models.IntegerChoices):
        TEST = 1, _('Test')
        PRESCRIPTION = 0, _('Prescription')
    type_test = models.IntegerField(choices=TypeTest.choices, default=TypeTest.PRESCRIPTION)
    content = models.FileField(storage=fs)
    doctor = models.ForeignKey(Doctor, on_delete=models.SET_NULL, null=True, blank=True)
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    test = models.ForeignKey('Test', on_delete=models.SET_NULL, null=True, blank=True)
    center = models.ForeignKey(Center, on_delete=models.SET_NULL, null=True, blank=True)
    def __str__(self):
        return self.receipt_no

class PickDay(models.IntegerChoices):
    MONDAY = 0, _('Monday')
    TUESDAY = 1, _('Tuesday')
    WEDNESDAY = 2, _('Wednesday')
    THURSDAY = 3, _('Thursday')
    FRIDAY = 4, _('Friday')
    SATURDAY = 5, _('Saturday')
    SUNDAY = 6, _('Sunday')

class Schedule(models.Model):
    start_time = models.TimeField()
    end_time = models.TimeField()
    day_of_week = models.IntegerField(choices=PickDay.choices)
    office_no = models.CharField(max_length=6)
    phone = models.CharField(max_length=20)
    fee_1st = models.CharField(max_length=6)
    fee_revisit = models.CharField(max_length=6)
    receptionist = models.ForeignKey(Employee, on_delete=models.SET_NULL, null=True, blank=True)
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE)
    center = models.ForeignKey(Center, on_delete=models.CASCADE)
    def __str__(self):
        return f"{self.get_day_of_week_display()}: office#{self.office_no} @{self.start_time}"
    def get_absolute_url(self):
        return "%i/" % self.id

class Token(models.Model):
    schedule = models.ForeignKey(Schedule, on_delete=models.CASCADE)
    date = models.DateField()
    tokenie_logged = models.BooleanField(default=False)
    serial = models.CharField(max_length=5)
    revisit = models.BooleanField(default=False)
    patient_name = models.CharField(max_length=50)
    patient = models.ForeignKey(Patient, on_delete=models.SET_NULL, null=True, blank=True)
    def __str__(self):
        return str(self.serial)
    def get_absolute_url(self):
        return "%i/" % self.id

class AppointmentHistory(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE)
    center = models.ForeignKey(Center, on_delete=models.CASCADE)
    datetime = models.DateTimeField()

class Reception(models.Model):
    center = models.ForeignKey(Center, on_delete=models.CASCADE)
    floor_no = models.CharField(max_length=20, null=True, blank=True)
    office_no = models.CharField(max_length=20, null=True, blank=True)
    phone = models.CharField(max_length=20)
    email = models.EmailField(null=True, blank=True)
    receptionist = models.ForeignKey(Employee, on_delete=models.SET_NULL, null=True, blank=True)
    active = models.BooleanField(default=False)

class Test(models.Model):
    name = models.CharField(max_length=30)

hosman_web/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.views.generic.edit import FormView
from django.views.generic import TemplateView
from hosman_web.modules.storage import store_gContent
from .models import Patient
from editorial.models import Center
from .forms import *
from .views_profile import *


# Create your views here.

def get_profile_view(request):
    if request.user.is_authenticated:
        url = "../profile/" + request.user.username + "/"
        return HttpResponseRedirect(url)
    return HttpResponseRedirect("../login/")

def ThankYouView(request):
    return HttpResponse("<h1>THANK YOU</h1>")

class GContentView(FormView):
    form_class = GContentForm
    template_name = "hosman_web/g_content.html"
    def post(self, request):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            g_content = form.save(commit=False)
            media = request.FILES['content']
            g_content.content = media
            g_content = store_gContent(request.user.username, g_content)
            g_content.save()
            url = f"../accounts/profile/{request.user.username}/"
            return HttpResponseRedirect(url)
        return render(request, self.template_name, {'form': form})
    def get(self, request):
        if request.user.is_authenticated:
            context = self.get_context_data()
            context['form'].fields['belongs_to'].initial = Patient.objects.get(user=request.user.id)
            return self.render_to_response(context)
        return HttpResponse("Error 610")

class IndexView(TemplateView):
    template_name = 'hosman_web/index.html'
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return HttpResponseRedirect("home/")
        context = self.get_context_data(**kwargs)
        context['index'] = True
        return self.render_to_response(context)

class HomeView(TemplateView):
    template_name = 'hosman_web/home.html'

hosman_web/templates/hosman_web/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  {% load static %}
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <link rel="stylesheet" href="{% static 'hosman_web/fa/css/all.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'hosman_web/css/bootstrap.min.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'hosman_web/css/style.css' %}">
    <title>H-care</title>
  </head>
  <body class="text-center">
    {% include "./header.html" %}
    {% block main %}{% endblock %}
    {% block content %}{% endblock %}
    {% include "./footer.html" %}
  </body>
</html>

hosman_web/templates/hosman_web/doctor_detail.html
{% extends "./base.html" %}
{% block main %}
<div class="container-fluid">
<h1>DR {{ object.first_name }} {{ object.last_name }}</h1>
<p>{{ object.phone }}</p>
</div>
{% endblock %}

hosman_web/templates/hosman_web/employee_detail.html

<h1>DR {{ object.first_name }} {{ object.last_name }}</h1>
<p>{{ object.phone }}</p>

hosman_web/templates/hosman_web/footer.html
{% load static %}
<footer class="fixed-bottom">
  <div id="nudge-bin">
    <p id="nudge-count">0</p>
    <button type="button"><i class="fa fa-fire" aria-hidden="true"></i></button>
  </div>
  <div class="row text-center bg-dark text-white">
    <p>All Rights Reserved.</p>
  </div>
  <script src="{% static 'hosman_web/js/jquery-3.5.1.min.js' %}"></script>
  <script src="{% static 'hosman_web/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'hosman_web/js/script.js' %}"></script>
</footer>

hosman_web/templates/hosman_web/g_content.html
{% extends "./base.html" %}
{% block content %}
<div class='container align-right'>
    <h3 class="text-center">Upload Media:</h3>
    <br>
    <form method="POST" class="content-right" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_ul }}
        <input type="submit" value="Upload">
    </form>
</div>
<br>
<br>
<br>
{% endblock %}

hosman_web/templates/hosman_web/header.html
{% load static %}
<header class="fixed-top">
  <div class="header-container">

    <div class="header-row header-row-1 bg-dark text-white">
      <a {% if user.is_authenticated %} href="http://{{ request.get_host }}/home/" {% else %} href="http://{{ request.get_host }}/" {% endif %} class="text-center brand">
        <!--<div class="header-icon" style="background-image: url({% static 'hosman_web/images/heartbeat-s.png' %});"></div>-->
        <img class="" src="{% static 'hosman_web/images/heartbeat-s.png' %}" width="30" height="30" alt="">
        <h6 class="header-title vertical-center">HeartBeat</h6>
      </a>
      
      <form action="http://{{ request.get_host }}/get/search/" method="GET">
        <div class="header-search">
          <input type="search" name="search" placeholder="Search" id="search-main" onfocus="toggleSearchFilterButton()"/>
          <button type="submit" class="search-icon text-dark" onclick="return srchEmpty()"><i class="fa fa-search" aria-hidden="true"></i></button>
          <button type="button" class="text-white" id="drop-filter" onclick="toggleSearchFilter()"><i class="fa fa-filter" aria-hidden="true" id="search-filter-button"></i></button>
        </div>
        <div class="" id="search-filter">
          <p>Search For: </p>
          <button id="search-filter-times" type="button"><i id="filter--ok" class="fa fa-times-circle"></i></button>
          <button id="search-filter-check" type="button"><i id="filter-ok" class="fa fa-check-circle"></i></button>
          <ul>
            <li>
              <label for="id_doctor">Doctor</label>
              <input type="checkbox" name="doctor" value="doctor" id="id_doctor" checked/>
            </li>
            <li>
              <label for="id_facility">Facility/Service</label>
              <input type="checkbox" name="facility" value="facility" id="id_facility" checked/>
            </li>
            <li>
              <label for="id_schedule">Appointment Schedule</label>
              <input type="checkbox" name="schedule" value="schedule" id="id_schedule" checked/>
            </li>
          </ul>
        </div>
        <div id="srch-main-suggestion" class="div-center-x"></div>
      </form>
    </div>
    <div class="header-row header-row-2" id="nav-div">

      {% if user.is_authenticated and not index %}
      <button class="expand-menu" name="nav-menu" id="nav-menu" type="button" onclick="toggleSideMenu()">
        <img id="nav-menu-icon" class="account-image" src="{{ request.profile_picture.0 }}" alt="IMG" width="50" height="50"/>
      </button>
      {% endif %}
      
      <div class="text-center" id="nav-option">
        <a href="http://{{ request.get_host }}/accounts/profile/" class="nav-btn nav-btn-5">
          <i class="fas fa-user-circle"></i>
        </a>
        {% if user.is_authenticated and not index %}
        <button class="nav-btn nav-btn-4" type="button"><i class="fa fa-calendar-check" aria-hidden="true"></i></button>
        <button class="nav-btn nav-btn-3" type="button"><i class="fa fa-archive" aria-hidden="true"></i></button>
        {% endif %}
        <button class="nav-btn nav-btn-2" type="button"><i class="fa fa-user-md" aria-hidden="true"></i></button>
        <button class="nav-btn nav-btn-1" type="button"><i class="fa fa-h-square" aria-hidden="true"></i></button>
      </div>

    </div>

  </div>
</header>

<nav>
  {% if user.is_authenticated and not index %}
  <div id="expanded-menu">
    <br>
    <br>
    <br>
    <br>
    <br>
    <ul>
      <li><button class="option-btn" onclick="toggleAccountsOption()">Accounts<i class="fa fa-chevron-circle-down" id="accounts-down" aria-hidden="true"></i><i class="fa fa-chevron-circle-up" id="accounts-up" aria-hidden="true"></i></button></li>
      <li>
        <div id="accounts-dropdown">
          <ul>
            {% if user.is_manager %}
            <li><a href="http://{{ request.get_host }}/admin/">Accounts {{ request.privilege.0 }}</a></li>
            {% endif %}
            <li><a href="#">Add Family</a></li>
            <li><a href="http://{{ request.get_host }}/accounts/profile/">Profile</a></li>
            <li><a href="http://{{ request.get_host }}/accounts/password_change/">Change Password</a></li>
            <li><a href="http://{{ request.get_host }}/accounts/logout/">Logout</a></li>
          </ul>
        </div>
      </li>
      <li><button class="option-btn">Appointments</button></li>
      <li><button class="option-btn">Med History</button></li>
      <li><button class="option-btn">Settings</button></li>
      <li><button class="option-btn">About</button></li>
      <li><button class="option-btn">Help</button></li>
      <li><button class="option-btn">Feedback</button></li>
      <li><button class="option-btn">Privacy Statement</button></li>
    </ul>
    <br>
    <br>
  </div>
  {% endif %}
</nav>

<br>
<br>
<br>
<br>

hosman_web/templates/hosman_web/home.html
{% extends "./base.html" %}
{% block main %}
<div class="container-fluid div-center">
    <h5>Welcome to HeartBeat.</h5>
    <p>Your personal health care assistant.</p>
</div>
{% endblock %}

hosman_web/templates/hosman_web/index.html
{% extends "./base.html" %}
{% block main %}
<div class="text-center div-center" id="greet-index">
    <h5>Welcome to HeartBeat.</h5>
    <p>Your personal health care assistant.</p>
    <br>
    <p>Please Login into your account:</p>
    <a class="btn-main" href="http://{{ request.get_host }}/accounts/login/">Login</a>
    <a class="btn-main" href="http://{{ request.get_host }}/accounts/signup/">Register</a>
</div>
{% endblock %}

hosman_web/templates/hosman_web/nurse_detail.html
<h1>DR {{ object.first_name }} {{ object.last_name }}</h1>
<p>{{ object.phone }}</p>

hosman_web/templates/hosman_web/user_detail.html
{% extends "./base.html" %}
{% load static %}
{% block main %}
<div class="container-fluid text-center">
  <br>
  <div class="profile-picture">
    <img src="/media/{{ picture }}" alt="IMG" style="height: 200px; width: 200px;">
    <button>UPDATE</button>
  </div>
  <h4>{{ patient.first_name }} {{ patient.last_name }}</h4>
  <hr>
  <div class="">
    <span class="btn-main">
      <button class="btn-main-left" type="button" name="about" onclick="showAbout(this)">Profile</button>
      <button class="btn-main-right"><a href="#"><i class="fas fa-edit" aria-hidden="true"></i>Edit</a></button>
    </span>
    <span class="btn-main">
      <button type="button" name="timeline" onclick="showTimeline(this)">History</button>
    </span>
  </div>
  <hr>
  <div class="container about">

    <div class="about" id="user-about" style="display: block;">
      <table>
        <tr>
          <td>Name</td>
          <td>{{ patient.first_name }} {{ patient.last_name }}</td>
        </tr>
        <tr>
          <td>Username</td>
          <td>{{ object.username }}</td>
        </tr>
        <tr>
          <td>Password</td>
          <td><a href="#">Change password</a></td>
        </tr>
        <tr>
          <td>Phone</td>
          <td>{{ patient.phone }}</td>
        </tr>
        <tr>
          <td>Email</td>
          <td>{{ patient.email }}</td>
        </tr>
        <tr>
          <td>Address</td>
          <td>{{ patient.address }}</td>
        </tr>
      </table>
      <br>
      <br>
      <br>
    </div>

    <div class="" id="user-timeline" style="display: none;">
      <p>{{ timeline }}</p>
      <br>
      <br>
      <br>
    </div>

  </div>
</div>
{% endblock %}